concurrency: ci-${{ github.ref }}
jobs:
  publish:
    container:
      image: eclipse-temurin:21-jdk
      options: --user root
    if: ${{ github.repository_owner == 'FabricMC' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: buildnumber
      name: Generate build number
      uses: onyxmueller/build-tag-number@v1
      with:
        prefix: build/${{ github.ref }}
        token: ${{ secrets.github_token }}
    - continue-on-error: true
      env:
        BRANCH_NAME: ${{ github.ref }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      run: ./gradlew build javadocJar checkVersion publish --stacktrace
name: Publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
