jobs:
  build:
    container:
      image: eclipse-temurin:21-jdk
      options: --user root
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      run: ./gradlew :filament:build :filament:publish --stacktrace --no-configuration-cache
name: Release Filament
on:
  repository_dispatch:
    types: trigger-ga___release-filament.yml
