jobs:
  update:
    if: ${{ github.event.label.name == 'update-base' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: FabricMC/fabric-action-scripts@v2
      with:
        context: yarn-update-base
name: Update Base Branch
on:
  repository_dispatch:
    types: trigger-ga___update-base.yml
